[build]
  base    = "DakLakCoffeeSupplyChain"   # app Next nằm trong subfolder này
  command = "npm ci && npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "18.20.3" }  # Node >= 18.17

[plugins]
  package = "@netlify/plugin-nextjs"     # dùng Netlify Next.js Runtime

# (tuỳ chọn) có thể chuyển hướng trang chủ về /dashboard hoặc /auth/login
# [[redirects]]
#   from = "/"
#   to   = "/dashboard"
#   status = 302
